//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ftss_tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ftss_tests.TestFiles", typeof(TestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I
        ///a
        ///about
        ///above
        ///across
        ///act
        ///active
        ///activity
        ///add
        ///afraid
        ///after
        ///again
        ///age
        ///ago
        ///agree
        ///air
        ///all
        ///alone
        ///along
        ///already
        ///always
        ///am
        ///amount
        ///an
        ///and
        ///angry
        ///another
        ///answer
        ///any
        ///anyone
        ///anything
        ///anytime
        ///appear
        ///apple
        ///are
        ///area
        ///arm
        ///army
        ///around
        ///arrive
        ///art
        ///as
        ///ask
        ///at
        ///attack
        ///aunt
        ///autumn
        ///away
        ///baby
        ///back
        ///bad
        ///bag
        ///ball
        ///bank
        ///base
        ///basket
        ///bath
        ///be
        ///bean
        ///bear
        ///beautiful
        ///bed
        ///bedroom
        ///beer
        ///before
        ///begin
        ///behave
        ///behind
        ///bell
        ///below
        ///besides
        ///best
        ///better
        ///between
        ///big
        ///bird
        ///birth
        ///birth [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string short_english_list {
            get {
                return ResourceManager.GetString("short_english_list", resourceCulture);
            }
        }
    }
}
