//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloomFilters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WordFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BloomFilters.WordFiles", typeof(WordFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA
        ///AB
        ///AD
        ///AE
        ///AG
        ///AH
        ///AI
        ///AL
        ///AM
        ///AN
        ///AR
        ///AS
        ///AT
        ///AW
        ///AX
        ///AY
        ///BA
        ///BE
        ///BI
        ///BO
        ///BY
        ///DA
        ///DE
        ///DO
        ///ED
        ///EF
        ///EH
        ///EL
        ///EM
        ///EN
        ///ER
        ///ES
        ///ET
        ///EW
        ///EX
        ///FA
        ///FE
        ///FI
        ///GI
        ///GO
        ///HA
        ///HE
        ///HI
        ///HM
        ///HO
        ///ID
        ///IF
        ///IN
        ///IS
        ///IT
        ///JO
        ///KA
        ///KI
        ///LA
        ///LI
        ///LO
        ///MA
        ///ME
        ///MI
        ///MM
        ///MO
        ///MU
        ///MY
        ///NA
        ///NE
        ///NO
        ///NU
        ///OD
        ///OE
        ///OF
        ///OH
        ///OI
        ///OM
        ///ON
        ///OO
        ///OP
        ///OR
        ///OS
        ///OU
        ///OW
        ///OX
        ///OY
        ///PA
        ///PE
        ///PI
        ///PO
        ///QI
        ///RE
        ///SH
        ///SI
        ///SO
        ///TA
        ///TE
        ///TI
        ///TO
        ///UH
        ///UM
        ///UN
        ///UP
        ///US
        ///UT
        ///WE
        ///WO
        ///XI
        ///XU
        ///YA
        ///YE
        ///YO
        ///ZA
        ///ZO
        ///AAH
        ///AAL
        ///AAS
        ///ABA
        ///ABB
        ///ABO
        ///ABS
        ///ABY
        ///ACE
        ///ACT
        ///ADD
        ///ADO
        ///ADS
        ///ADZ
        ///AF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GW20P {
            get {
                return ResourceManager.GetString("GW20P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2g1c
        ///2 girls 1 cup
        ///acrotomophilia
        ///alabama hot pocket
        ///alaskan pipeline
        ///anal
        ///anilingus
        ///anus
        ///apeshit
        ///arsehole
        ///ass
        ///asshole
        ///assmunch
        ///auto erotic
        ///autoerotic
        ///babeland
        ///baby batter
        ///baby juice
        ///ball gag
        ///ball gravy
        ///ball kicking
        ///ball licking
        ///ball sack
        ///ball sucking
        ///bangbros
        ///bangbus
        ///bareback
        ///barely legal
        ///barenaked
        ///bastard
        ///bastardo
        ///bastinado
        ///bbw
        ///bdsm
        ///beaner
        ///beaners
        ///beaver cleaver
        ///beaver lips
        ///beastiality
        ///bestiality
        ///big black
        ///big breasts
        ///big knockers
        ///big tits
        ///bimbos
        ///birdlock
        ///bitc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LNOOBW_en {
            get {
                return ResourceManager.GetString("LNOOBW_en", resourceCulture);
            }
        }
    }
}
